[package]
name = "enumstr"
version = "0.1.0"
authors = ["Dor <commo64dor@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["parsing", "derive", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
